maps:
  Beacon:
    type: SOLO
    maxPlayers: 4
    generators:
      - 'iron;61.5;65.5;0.5'
      - 'iron;0.5;65.5;-60.5'
      - 'iron;-60.5;65.5;0.5'
      - 'iron;0.5;65.5;61.5'
      - 'diamond;42.5;67;42.5'
      - 'diamond;-41.5;67;42.5'
      - 'diamond;42.5;67;-41.5'
      - 'diamond;-41.5;67;-41.5'
      - 'emerald;-8.5;70;0.5'
      - 'emerald;0.5;70;-8.5'
      - 'emerald;9.5;70;0.5'
      - 'emerald;0.5;70;9.5'
    itemShops: {}
    teamUpgrades: {}
    teams:
      'Red':
        spawnpoint: ''
      'Yellow':
        spawnpoint: ''
      'Green':
        spawnpoint: ''
      'Blue':
        spawnpoint: ''