maps:
  Beacon:
    type: SOLO
    maxPlayers: 4
    generators:
      - 'iron;61.5;65.5;0.5'
      - 'iron;0.5;65.5;-60.5'
      - 'iron;-60.5;65.5;0.5'
      - 'iron;0.5;65.5;61.5'
      - 'diamond;42.5;67;42.5'
      - 'diamond;-41.5;67;42.5'
      - 'diamond;42.5;67;-41.5'
      - 'diamond;-41.5;67;-41.5'
      - 'emerald;-8.5;70;0.5'
      - 'emerald;0.5;70;-8.5'
      - 'emerald;9.5;70;0.5'
      - 'emerald;0.5;70;9.5'
    itemShops:
      - '-55.5;66;-5.5'
      - '6.5;66;-55.5'
      - '56.5;66;6.5'
      - '-5.5;66;56.5'
    teamUpgrades:
      - '6.5;66;56.5'
      - '-55.5;66;6.5'
      - '-5.5;66;-55.5'
      - '56.5;66;-5.5'
    spawnpoints:
      - 'Yellow;-57.5;66;0.5'
      - 'Blue;0.5;66;-57.5'
      - 'Green;58.5;66;0.5'
      - 'Red;0.5;66;58.5'