maps:
  Beacon:
    gamemode: solo
    world: 'Bedwars1'
    maxPlayers: 4
    diamondGenerators:
      '1':
        x: 42.5
        y: 63
        z: 42.5
      '2':
        x: -42.5
        y: 63
        z: 42.5
      '3':
        x: 42.5
        y: 63
        z: -42.5
      '4':
        x: -42.5
        y: 63
        z: -42.5
    itemShops:
      '1':
        x:
        y:
        z:
        yaw:
        pitch:
    teamUpgrades: {}
    teams:
      'Red':
        spawnpoint: ''
      'Yellow':
        spawnpoint: ''
      'Green':
        spawnpoint: ''
      'Blue':
        spawnpoint: ''