name: Bedwars
version: 1.0.0
main: me.ezrichards.bedwars.Bedwars
author: ezrichards
api-version: '1.20'
softdepend: [HolographicDisplays, Citizens]

commands:
  map:
    description: Modify maps.
    usage: /map
  world:
    description: World management commands.
    usage: /world