name: Bedwars
version: 1.0.0
main: me.erichards.bedwars.Bedwars
author: erichards
api-version: '1.16'
softdepend: [HolographicDisplays, Citizens]

commands:
  map:
    description: Modify maps.
    usage: /map
  world:
    description: World management commands.
    usage: /world